"""Add message column to venue and artist tables

Revision ID: 7f840739afff
Revises: 666caa9e5039
Create Date: 2020-04-26 15:45:29.543001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f840739afff'
down_revision = '666caa9e5039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_message', sa.String(), nullable=True))
    op.add_column('venue', sa.Column('seeking_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'seeking_message')
    op.drop_column('artist', 'seeking_message')
    # ### end Alembic commands ###
